### ISSUE TITLE
Use the Device Control knobs for... well... Device Control.

### ISSUE THREAD

**Issue by EmilySieben** [git-moss/APC4Bitwig#10]
I would like to assign the upper knobs (in mode "user") of my APC40 mkII by hand, and use the "Device Control" knobs for the Device Macros. That's the way how Ableton is doing it.

Is there an easy way to do this?

**Comment by git-moss** [comment]
You would need to change the script. Exchange the MacroMode with the device knobs and put the user mapping in place.
