### ISSUE TITLE
Question: How to prevent scroll on track selection

### ISSUE THREAD

**Issue by mcskelle** [git-moss/APC4Bitwig#11]
Hi there - first thank you so much for your bitwig scripts

Is it possible to not have the the 5x8 grid move around when i track select?

Im trying to use a apc 20 + apc40 side by side. I dont need to move the grids as the two controllers cover all my 16 tracks. Of couse the device selection and other stuff happening with a track selection is great, its hust the grid that moves that I'd like to disable.

regards
/thomas

**Comment by git-moss** [comment]
Sorry, that is currently not possible. All my scripts are designed to follow the Bitwig UI states. You would need to change this to an independent navigation.
