### ISSUE TITLE
Entering Chain Device Layer - possible?

### ISSUE THREAD

**Issue by weasei** [git-moss/APC4Bitwig#12]
Hi,

if I have a chain device containing multiple devices, would it be possible to enter them from the regular device chain if the chain is selected (in the same way as when you have an instrument layer)? when i click inside the chain i can go back to the upper layer but only enter the chain by clicking inside these 'nested' devices with the mouse.
Or is this maybe restricted by the API?
I would try implementing it myself but maybe you can tell me right away it's not possible.

Would appreciate your advice, great software altogether.

Best regards,

Simon

**Comment by git-moss** [comment]
Yes, it is possible but it is not trivial. You can look at the respective code in Push4Bitwig. Look in AbstractViewExtensions.js ( https://github.com/git-moss/Push4Bitwig/blob/master/view/AbstractViewExtensions.js ) at the functions AbstractView.prototype.onDeviceLeft and AbstractView.prototype.onDeviceRight.
Good luck :-)
