### ISSUE TITLE
Device control still not working

### ISSUE THREAD

**Issue by abique** [git-moss/APC4Bitwig#4]
Hi,
I'm on master and device control is still not working well: take a new plugin and create the device control for it, it will not work.
Cheers, Alex.

**Comment by git-moss** [comment]
Hi Alex,
I could not reproduce a problem with master bus. Could you please give some more details? What platform and version are you on? Which plugin are you using? What means "will not work"? Are there errors reported in the Controller Script Console?
Cheers.

**Comment by abique** [comment]
Hey, sorry my report was not clear.
I'm using Bitwig 1.1.5 on Linux. U-HE Bazille. APC4Bitwig from master. So everything is latest revision.
To reproduce my bug I'd say:
1) start bitwig without any device control for Bazille. (common parameters right? :))
2) Then try to setup some device control for Bazille, like the osc1 fractal distortion.

For me that does not work.
Thanks a lot :)

**Comment by git-moss** [comment]
Ah, now I understand. You ran into that one:
https://github.com/teotigraphix/Framework4Bitwig/issues/47
