### ISSUE TITLE
Device control knobs doesn't affect the device

### ISSUE THREAD

**Issue by tam4s** [git-moss/APC4Bitwig#6]
The device control knobs on APC 40 (MK1) don't work: They do not change the values of the selected device. Only the `DEVICE ON/OFF` and the `CLIP/TRACK` buttons work from the device section of the APC 40. 

I am using the very latest control script from the github repo, Bitwig 1.2 Beta 10 and APC 40 (MK1) and I have a mac book pro.

**Comment by git-moss** [comment]
I tested again with 1.2 and did not spot a problem. Please retry with version I just released.
