### ISSUE TITLE
Linux & APC40 mkII: tracks with midi input selected arm for recording when selected using arrow buttons

### ISSUE THREAD

**Issue by RobinFen** [git-moss/APC4Bitwig#8]
Hi, first of all, this is amazing work you're dong.

On my linux machine (bitwig 1.3.6), moving over a track using the arrow buttons on my APC40mkII arms the tracks for recording (and enables the column of red buttons on the controller). As a workaround I had to remove all the mini inputs from my track to prevent this from happening in my projects.

**Comment by git-moss** [comment]
By "moving over a track" you mean you scroll through the tracks with the cursor keys? 
What are your rec enable settings in the properties dialog?

**Comment by RobinFen** [comment]
ah, I see now what's happening. I had no idea that was an option!
