### ISSUE TITLE
APC40 MKII: Shift + Session enables automation write in clip launcher

### ISSUE THREAD

**Issue by abique** [git-moss/APC4Bitwig#9]
Hi,

I did not find how to enable automation write in clip launcher so I made a suggestion.
Maybe there is a better way?

![screenshot_20160418_004659](https://cloud.githubusercontent.com/assets/31200/14590604/6af176dc-04ff-11e6-8dbb-ee1329a392ad.png)

Regards,
Alex

**Comment by git-moss** [comment]
Implemented in 3.05.

**Comment by abique** [comment]
Thank you :)

**Comment by abique** [comment]
Works fine here.
